config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :luci

  root 'home#index'

end

app/models/luce.rb
class Luce < ActiveRecord::Base

    validates :f1,:presence => {:message=>" non può essere vuoto"}
    validates :f2,:presence => {:message=>"non può essere vuoto"}
    validates :f3,:presence => {:message=>"non può essere vuoto"}
    validates :euro_fornitura,:presence => {:message=>"non può essere vuoto"}
    validates :euro_pagato,:presence => {:message=>"non può essere vuoto"}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    today = Date.today
    start = Date.new(today.year,1,1)

    @energia_sum_anno = Luce.select("SUM(luci.f1) as sum_f1, SUM(luci.f2) as sum_f2, SUM(luci.f3) as sum_f3, SUM(luci.f1+ luci.f2 +luci.f3) as sum_tot, SUM(luci.euro_fornitura) as sum_fornitura, SUM(luci.euro_pagato) as sum_pagato").where("dal between ? and ? or al between ? and ?","#{start}","#{today}","#{start}","#{today}")[0]
    @energia_avg_anno = Luce.select("avg(luci.f1) as avg_f1, avg(luci.f2) as avg_f2, avg(luci.f3) as avg_f3, avg(luci.f1+ luci.f2 +luci.f3) as avg_tot, avg(luci.euro_fornitura) as avg_fornitura, avg(luci.euro_pagato) as avg_pagato").where("dal between ? and ? or al between ? and ?","#{start}","#{today}","#{start}","#{today}")[0]
  end
end

app/controllers/luci_controller.rb
class LuciController < ApplicationController
  before_action :set_luce, only: [:show, :edit, :update, :destroy]

  # GET /luci
  # GET /luci.json
  def index
    @luci = Luce.all
  end

  # GET /luci/1
  # GET /luci/1.json
  def show
  end

  # GET /luci/new
  def new
    @luce = Luce.new
  end

  # GET /luci/1/edit
  def edit
  end

  # POST /luci
  # POST /luci.json
  def create
    @luce = Luce.new(luce_params)

    @luce.dal = DateTime.strptime(luce_params[:dal]+"-01", "%Y-%m-%d")
    val = luce_params[:al].split("-")
    @luce.al = Date.new(val[0].to_i,val[1].to_i,-1)

    respond_to do |format|
      if @luce.save
        format.html { redirect_to @luce, notice: 'Bolletta Luce inserita correttamente.' }
        format.json { render :show, status: :created, location: @luce }
      else
        format.html { render :new }
        format.json { render json: @luce.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /luci/1
  # PATCH/PUT /luci/1.json
  def update
    respond_to do |format|

      luce_params[:dal] = DateTime.strptime(luce_params[:dal]+"-01", "%Y-%m-%d")
      val = luce_params[:al].split("-")
      luce_params[:al] = Date.new(val[0].to_i,val[1].to_i,-1)

      if @luce.update(luce_params)
        format.html { redirect_to @luce, notice: 'Bolletta Luce aggiornata correttamente.' }
        format.json { render :show, status: :ok, location: @luce }
      else
        format.html { render :edit }
        format.json { render json: @luce.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /luci/1
  # DELETE /luci/1.json
  def destroy
    @luce.destroy
    respond_to do |format|
      format.html { redirect_to luci_url, notice: 'Bolletta Luce eliminata correttamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_luce
      @luce = Luce.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def luce_params
      params.require(:luce).permit(:dal, :al, :f1, :f2, :f3, :euro_fornitura, :euro_pagato, :note)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/luci_helper.rb
module LuciHelper
end

app/views/home/index.html.erb
<header class="navbar navbar-expand-lg navbar-light bg-light">
    <!-- Navigation -->
    <a class="navbar-brand" href="#">Spese di Casa</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
            <li class="nav-item active" data-toggle="tooltip" data-placement="right" title="Dashboard">
                <a class="nav-link" href="#">
                    <i class="fa fa-fw fa-dashboard"></i>
                    <span class="nav-link-text">
                Dashboard</span>
                </a>
            </li>
            <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Bollette Luce">
                <a class="nav-link" href="/luci">
                    <i class="fa fa-fw fa-bolt"></i>
                    <span class="nav-link-text">
                Bollette Luce</span>
                </a>
            </li>
    </div>
</header>

<div class="content-wrapper">

    <div class="container-fluid">

        <!-- Breadcrumbs -->
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="#">Dashboard</a>
            </li>
            <li class="breadcrumb-item active">My Dashboard</li>
        </ol>

        <!-- Icon Cards -->
        <div class="row">
            <div class="col-xl-3 col-sm-6 mb-3">
                <div class="card text-white bg-info o-hidden h-100">
                    <div class="card-body">
                        <h6 class="card-title"><i class="fa fa-bolt"></i>&nbsp;Totali CONSUMI
                            <%= DateTime.now.year %>
                        </h6>
                        <div class="mr-5">
                            <div style="font-size:2em">F1<span class="float-right">
                                <%= @energia_sum_anno.sum_f1 %> KWh</span></div>
                            <div style="font-size:2em">F2<span class="float-right">
                                <%= @energia_sum_anno.sum_f2 %> KWh</span></div>
                            <div style="font-size:2em">F3<span class="float-right">
                                <%= @energia_sum_anno.sum_f3 %> KWh</span></div>
                            <div style="font-size:2em">Tot<span class="float-right">
                                <%= @energia_sum_anno.sum_tot %> KWh</span></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xl-3 col-sm-6 mb-3">
                <div class="card text-white bg-primary o-hidden h-100">
                    <div class="card-body">
                        <h6 class="card-title"><i class="fa fa-bolt"></i>&nbsp;Totali SPESE
                            <%= DateTime.now.year %>
                        </h6>
                        <div class="mr-5">
                            <div style="font-size:2em">
                                Fornitura<span class="float-right">
                                <%= number_to_currency(@energia_sum_anno.sum_fornitura, options = {unit: "€", separator: ",", delimiter: ".", format: "%n %u"}) %>
                                  </span>
                            </div>
                            <div style="font-size:2em">
                                Altro<span class="float-right">
                                <%= number_to_currency(@energia_sum_anno.sum_pagato-@energia_sum_anno.sum_fornitura, options = {unit: "€", separator: ",", delimiter: ".", format: "%n %u"}) %>
                              </span>
                            </div>
                            <div style="font-size:2em">
                                Totale<span class="float-right">
                                <%= number_to_currency(@energia_sum_anno.sum_pagato, options = {unit: "€", separator: ",", delimiter: ".", format: "%n %u"}) %>
                              </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xl-3 col-sm-6 mb-3">
                <div class="card text-white bg-info o-hidden h-100">
                    <div class="card-body">
                        <h6 class="card-title"><i class="fa fa-bolt"></i>&nbsp;Media CONSUMI
                            <%= DateTime.now.year %>
                        </h6>
                        <div class="mr-5">
                            <div style="font-size:2em">F1<span class="float-right">
                                    <%= @energia_avg_anno.avg_f1 %> KWh</span></div>
                            <div style="font-size:2em">F2<span class="float-right">
                                    <%= @energia_avg_anno.avg_f2 %> KWh</span></div>
                            <div style="font-size:2em">F3<span class="float-right">
                                    <%= @energia_avg_anno.avg_f3 %> KWh</span></div>
                            <div style="font-size:2em">Tot<span class="float-right">
                                    <%= @energia_avg_anno.avg_tot %> KWh</span></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xl-3 col-sm-6 mb-3">
                <div class="card text-white bg-primary o-hidden h-100">
                    <div class="card-body">
                        <h6 class="card-title"><i class="fa fa-bolt"></i>&nbsp;Media SPESE
                            <%= DateTime.now.year %>
                        </h6>
                        <div class="mr-5">
                            <div style="font-size:2em">
                                Fornitura<span class="float-right">
                                <%= number_to_currency(@energia_avg_anno.avg_fornitura, options = {unit: "€", separator: ",", delimiter: ".", format: "%n %u"}) %>
                                  </span>
                            </div>
                            <div style="font-size:2em">
                                Altro<span class="float-right">
                                <%= number_to_currency(@energia_avg_anno.avg_pagato-@energia_avg_anno.avg_fornitura, options = {unit: "€", separator: ",", delimiter: ".", format: "%n %u"}) %>
                              </span>
                            </div>
                            <div style="font-size:2em">
                                Totale<span class="float-right">
                                <%= number_to_currency(@energia_avg_anno.avg_pagato, options = {unit: "€", separator: ",", delimiter: ".", format: "%n %u"}) %>
                              </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Consumi Energia -->
        <div class="card mb-3">
            <div class="card-header">
                <i class="fa fa-area-chart"></i> Consumi Energia
            </div>
            <div class="card-body">
                <div id="plot_energia" style="width:100%;height:300px"></div>
            </div>
        </div>

        <div class="row">

        </div>

    </div>
    <!-- /.container-fluid -->

</div>
<!-- /.content-wrapper -->

<footer class="sticky-footer">
    <div class="container">
        <div class="text-center">
            <small>Copyright &copy; Your Website 2017</small>
        </div>
    </div>
</footer>

<!-- Scroll to Top Button -->
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fa fa-angle-up"></i>
</a>

<!-- Logout Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            </div>
            <div class="modal-body">
                Select "Logout" below if you are ready to end your current session.
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <a class="btn btn-primary" href="login.html">Logout</a>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Spesecasa</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/luci/_form.html.erb
<%= form_for(@luce) do |f| %>
    <% if @luce.errors.any? %>
        <div id="error_explanation">
            <h2>
                <%= pluralize(@luce.errors.count, "error") %> prohibited this luce from being saved:</h2>

            <ul>
                <% @luce.errors.full_messages.each do |message| %>
                    <li>
                        <%= message %>
                    </li>
                    <% end %>
            </ul>
        </div>
        <% end %>

            <div class="form-group">
                <%= f.label :dal %>
                    <div class="form-inline">
                        <%= f.text_field :dal, type: :month, class: "form-control", :value => @luce.dal.strftime("%Y-%m") %>
                    </div>
            </div>
            <div class="form-group">
                <%= f.label :al %>
                    <div class="form-inline">
                        <%= f.text_field :al, type: :month, class: "form-control", :value => @luce.al.strftime("%Y-%m") %>
                    </div>
            </div>
            <div class="form-group">
                <%= f.label :f1 %>
                    <%= f.number_field :f1, {:class => "form-control"} %>
            </div>
            <div class="form-group">
                <%= f.label :f2 %>
                    <%= f.number_field :f2, {:class => "form-control"} %>
            </div>
            <div class="form-group">
                <%= f.label :f3 %>
                    <%= f.number_field :f3, {:class => "form-control"} %>
            </div>
            <div class="form-group">
                <%= f.label :euro_fornitura %>
                    <%= f.text_field :euro_fornitura, {:class => "form-control"} %>
            </div>
            <div class="form-group">
                <%= f.label :euro_pagato %>
                    <%= f.text_field :euro_pagato, {:class => "form-control"} %>
            </div>
            <div class="form-group">
                <%= f.label :note %>
                    <%= f.text_area :note, {:class => "form-control"} %>
            </div>
            <div class="actions">
                <%= f.submit 'Salva', :class => "btn btn-outline-primary" %>
            </div>
            <br><br>
            <% end %>

app/views/luci/edit.html.erb
<header class="navbar navbar-expand-lg navbar-light bg-light">
    <!-- Navigation -->
    <a class="navbar-brand" href="#">Spese di Casa</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
            <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
                <a class="nav-link" href="/">
                    <i class="fa fa-fw fa-dashboard"></i>
                    <span class="nav-link-text">
                        Dashboard</span>
                </a>
            </li>
            <li class="nav-item active" data-toggle="tooltip" data-placement="right" title="Bollette Luce">
                <a class="nav-link" href="/luci">
                    <i class="fa fa-fw fa-bolt"></i>
                    <span class="nav-link-text">
                        Bollette Luce</span>
                </a>
            </li>
    </div>
</header>
<div class="content-wrapper">
    <div class="container-fluid">

        <!-- Breadcrumbs -->
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="#">Bollette Luce</a>
            </li>
            <li class="breadcrumb-item">
                <a href="/luci">Elenco</a>
            </li>
            <li class="breadcrumb-item active">Inserimento</li>
        </ol>

        <p></p>
        <h1>Modifica Bolletta Luce
            <%= link_to 'Indietro', luci_path, class: "btn btn-outline-primary float-right" %>
                <%= link_to 'Vedi', @luce, class: "btn btn-outline-primary float-right", style: "margin-right:15px" %>
        </h1>

        <%= render 'form' %>
    </div>
</div>

app/views/luci/index.html.erb
<header class="navbar navbar-expand-lg navbar-light bg-light">
    <!-- Navigation -->
    <a class="navbar-brand" href="#">Spese di Casa</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
            <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
                <a class="nav-link" href="/">
                    <i class="fa fa-fw fa-dashboard"></i>
                    <span class="nav-link-text">
                    Dashboard</span>
                </a>
            </li>
            <li class="nav-item active" data-toggle="tooltip" data-placement="right" title="Bollette Luce">
                <a class="nav-link" href="/luci">
                    <i class="fa fa-fw fa-bolt"></i>
                    <span class="nav-link-text">
                    Bollette Luce</span>
                </a>
            </li>
    </div>
</header>
<div class="content-wrapper">
    <div class="container-fluid">

        <!-- Breadcrumbs -->
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="#">Bollette Luce</a>
            </li>
            <li class="breadcrumb-item active">Elenco</li>
        </ol>

        <p id="notice">
            <%= notice %>
        </p>

        <h1>Elenco Bolletta Luce
            <%= link_to 'Inserisci', new_luce_path, class: "btn btn-outline-primary float-right" %>
        </h1>

        <table class="table table-striped table-responsive table-bordered">
            <thead>
                <tr>
                    <th colspan="2" class="text-center">Periodo</th>
                    <th colspan="3" class="text-center">KWh</th>
                    <th colspan="2" class="text-center">&euro;</th>
                    <th colspan="3" class="text-center">&nbsp;</th>
                </tr>
                <tr>
                    <th>Dal</th>
                    <th>Al</th>
                    <th>F1</th>
                    <th>F2</th>
                    <th>F3</th>
                    <th>Euro fornitura</th>
                    <th>Euro pagato</th>
                    <th>Note</th>
                    <th colspan="2"></th>
                </tr>
            </thead>

            <tbody>
                <% @luci.each do |luce| %>
                    <tr>
                        <td>
                            <%= luce.dal.strftime('%b %Y') %>
                        </td>
                        <td>
                            <%= luce.al.strftime('%b %Y') %>
                        </td>
                        <td>
                            <%= luce.f1 %>
                        </td>
                        <td>
                            <%= luce.f2 %>
                        </td>
                        <td>
                            <%= luce.f3 %>
                        </td>
                        <td>
                            <%= number_with_precision(luce.euro_fornitura, delimiter: ".", separator: ",", precision: 2) %>
                        </td>
                        <td>
                            <%= number_with_precision(luce.euro_pagato, delimiter: ".", separator: ",", precision: 2) %>
                        </td>
                        <td>
                            <%= luce.note %>
                        </td>
                        <td>
                            <%= link_to 'Modifica', edit_luce_path(luce) %>
                        </td>
                        <td>
                            <%= link_to 'Elimina', luce, method: :delete, data: { confirm: 'Sei sicuro?' } %>
                        </td>
                    </tr>
                    <% end %>
            </tbody>
        </table>
    </div>
</div>

app/views/luci/new.html.erb
<header class="navbar navbar-expand-lg navbar-light bg-light">
    <!-- Navigation -->
    <a class="navbar-brand" href="#">Spese di Casa</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
            <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
                <a class="nav-link" href="/">
                    <i class="fa fa-fw fa-dashboard"></i>
                    <span class="nav-link-text">
                        Dashboard</span>
                </a>
            </li>
            <li class="nav-item active" data-toggle="tooltip" data-placement="right" title="Bollette Luce">
                <a class="nav-link" href="/luci">
                    <i class="fa fa-fw fa-bolt"></i>
                    <span class="nav-link-text">
                        Bollette Luce</span>
                </a>
            </li>
    </div>
</header>
<div class="content-wrapper">
    <div class="container-fluid">

        <!-- Breadcrumbs -->
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="#">Bollette Luce</a>
            </li>
            <li class="breadcrumb-item">
                <a href="/luci">Elenco</a>
            </li>
            <li class="breadcrumb-item active">Inserimento</li>
        </ol>

        <p></p>
        <h1>Inserisci Bolletta Luce
            <%= link_to 'Indietro', luci_path, class: "btn btn-outline-primary float-right" %>
        </h1>
        <%= render 'form' %>
    </div>
</div>

app/views/luci/show.html.erb
<div class="container">
  <div class="card">
    <div class="card-header">
      Bolletta Luce
      <%= link_to 'Indietro', luci_path,  class: "btn btn-sm btn-outline-primary float-right" %>
    </div>
    <div class="card-body">
      <p id="notice">
          <%= notice %>
      </p>

      <p>
          <strong>Dal:</strong>
          <%= @luce.dal.strftime('%b %Y') %>
      </p>

      <p>
          <strong>Al:</strong>
          <%= @luce.al.strftime('%b %Y') %>
      </p>

      <p>
          <strong>F1:</strong>
          <%= @luce.f1 %>
      </p>

      <p>
          <strong>F2:</strong>
          <%= @luce.f2 %>
      </p>

      <p>
          <strong>F3:</strong>
          <%= @luce.f3 %>
      </p>

      <p>
          <strong>Euro fornitura:</strong>
          <%= @luce.euro_fornitura %>
      </p>

      <p>
          <strong>Euro pagato:</strong>
          <%= @luce.euro_pagato %>
      </p>

      <p>
          <strong>Note:</strong>
          <%= @luce.note %>
      </p>
    </div>
    <div class="card-footer">
      <%= link_to 'Modifica', edit_luce_path(@luce),  class: "btn btn-sm btn-outline-primary float-right" %>
    </div>
  </div>
</div>